name = "cloud-health"
main = "worker.ts"
compatibility_date = "2025-04-01"

[assets]
directory = "./dist"

[build]
command = "npm run build"
watch_dir = ["src", "server", "worker.ts"]

[[d1_databases]]
binding = "DB"
database_name = "cloud-health-db"
database_id = "D1_DATABASE_ID"

[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "KV_AUTH_TOKENS_ID"

[[kv_namespaces]]
binding = "VERIFICATION_CODES"
id = "KV_VERIFICATION_CODES_ID"

# D1 Database:
#   - DB
#
# KV Namespaces:
#   - AUTH_TOKENS
#   - VERIFICATION_CODES
#
# Variables:
#   - TURNSTILE_SITE_KEY
#
# Secrets:
#   - TURNSTILE_SECRET_KEY
#   - RESEND_API_KEY
#   - ADMIN_USERNAME
#   - ADMIN_PASSWORD
